### ISSUE TITLE
Login não está funcionando

### ISSUE THREAD

**Issue by gdbarros94** [gdbarros94/gerenciamento-Escolar#31]
inicio no site classmanager.alunostds.dev.br e ao realizar o login sou redirecionado para 127.0.0.1:5000 e ao forçar a url novamente para classmanager.alunostds.dev.br/admin apresenta o erro ``` werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.gerenciar_usuarios'. Did you mean 'main.serve_image' instead? ```

**Comment by KerubinDev** [comment]
Arrumado, o erro estava no tipo de rota e na rota não existir

**Comment by gdbarros94** [comment]
solucionado
