### ISSUE TITLE
tela inicial 

### ISSUE THREAD

**Issue by gdbarros94** [gdbarros94/gerenciamento-Escolar#32]
na tela inicial o menu lateral deve iniciar recolhido, e o icone do menu deve mudar, quando aberto uma seta para a esquerda para recolhe-lo, quando estiver recolhido o icone de hamburguer (3 linhas)
no conteúdo da tela inicial deve-se remover o grafico, e mostrar somente as salas agendadas para o turno corrente. 
use a função turno_atual para retornar o turno corrente e enviar para o frontend, o frontend deve receber um objeto com todos os agendamentos do dia e tratar com js para o turno corrente.

**Comment by felipeGJsilva** [comment]
já foi feito

**Comment by gdbarros94** [comment]
solucioinado
