### ISSUE TITLE
Arrumar a Seta de retorno

### ISSUE THREAD

**Issue by VitorNoe** [gdbarros94/gerenciamento-Escolar#56]
Ao acessar Gerenciar Usuários, uma seta azul no canto superior esquerdo será exibido na tela para retornar ao painel, porem não esta respondendo.
![Captura de tela 2024-10-15 192149](https://github.com/user-attachments/assets/482b690f-6ca7-4581-ac57-6df93a4adf18)

**Comment by VitorNoe** [comment]
A seta está funcionando bem.

**Comment by gdbarros94** [comment]
solucionado
