### ISSUE TITLE
Erro de Imagem "Logo do Sistema" na pagina Gerenciar usuarios.

### ISSUE THREAD

**Issue by VitorNoe** [gdbarros94/gerenciamento-Escolar#60]
Ao acessar a pagina do sistema de cadastro, aparenta exibir uma imagem no topo, porem ele não esta sendo exibida.
![Captura de tela 2024-10-15 200400](https://github.com/user-attachments/assets/863bff73-9561-495f-a18e-81d1404efa21)

**Comment by AlanCornely** [comment]
Erro resolvido.
![image](https://github.com/user-attachments/assets/eab06f6b-5dc8-40bb-904c-e9e8d10a4842)

**Comment by gdbarros94** [comment]
Solucionado
